apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "cluster-infra.limitRangePods" . }}
spec:
  limits:
  - max:
      cpu: "1000m"
      memory: "600M"
    min:
      cpu: "50m"
      memory: "50M"
    default:
      cpu: "1000m"
      memory: "600M"
    defaultRequest:
      cpu: "50m"
      memory: "50M"
    type: Container