apiVersion: v1
kind: Service
metadata:
  name: {{ include "ncms.fullname" . }}
  labels:
    {{- include "ncms.labels" . | nindent 4 }}
  annotations:   
   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  loadBalancerIP:  {{ .Values.service.loadBalancerIP }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ncms.selectorLabels" . | nindent 4 }}   