apiVersion: v1
kind: Service
metadata:
  name: my-mynaati-release-mynaati # Derived from `mynaati.fullname`
  labels:
    helm.sh/chart: mynaati-1.0.0 # Derived from `mynaati.chart`
    app.kubernetes.io/name: mynaati # Derived from `mynaati.name`
    app.kubernetes.io/instance: my-mynaati-release # Derived from .Release.Name
    app.kubernetes.io/version: "1.0.0" # Assuming .Chart.AppVersion is 1.0.0
    app.kubernetes.io/managed-by: Helm # Derived from .Release.Service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  loadBalancerIP: 10.50.4.101 # From .Values.service.loadBalancerIP
  type: LoadBalancer # From .Values.service.type
  ports:
    - port: 80 # From .Values.service.port
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: mynaati # Derived from `mynaati.name`
    app.kubernetes.io/instance: my-mynaati-release # Derived from .Release.Name