replicaCount: 1

image:
  repository: naatidevacri0q0.azurecr.io/naatidevacri0q0.azurecr.io/mynaatiui
  tag: "20250730.14"  # Use the same working tag pattern
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: acr-secret-new

serviceAccount:
  name: kv-reader-sa     

podSecurityContext: {}

containerSecurityContext: {}

nodeName: akse2asv5000000

persistentStorage:
  claimName: dev-naati-volume-claim
  mountPath: /storage

tempPersistentStorage:
  claimName: dev-naati-temp-volume-claim
  mountPath: /tempStorage

env:
  KeyVaultUrl: https://naati-dev-kv-jyrb.vault.azure.net/

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

service:
  type: LoadBalancer
  port: 80
  targetPort: http
  loadBalancerIP: 10.50.4.101
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"

resources: {}

affinity: {}

tolerations: []

terminationGracePeriodSeconds: 15

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  cpu:
    averageUtilization: 80

config:
  CertificationApiLimit: "3"
  aspnet_MaxJsonDeserializerMembers: "160000"
  "ExternalUrl_Applications_URL": "https://uatmynaati.naati.com.au/apply"
  "BypassExaminerAuthentication": "true"
  "kosettings_allowEmailPaste": "true"
  "kosettings_skipRecaptcha": "true" 
  "EnvironmentType": "Uat"
  "EnvironmentName": "UAT_CLOUD"
  "SecretPrefix": "UAT"
      # Internal ip of Ncms
  #     "NcmsUrl": "http://10.50.7.200"
  #     "SecurePay_PaymentUrl": "https://test.securepay.com.au/xmlapi/payment"
  #     "DebugMode" : "False"
  #     "EnableSwagger" : "False"
  #     "logging_MinimumLevel": "Information"
  #     "AccountingOperationsReportEmailsTo": "UAT_Batching@altf4solutions.com.au;Pasindu.Wijayatilaka@f1solutions.com.au;Josh.Yip@f1solutions.com.au;Hector.Figueroa@f1solutions.com.au"
  #     "EmailBatchingReportEmailsTo": "UAT_Batching@altf4solutions.com.au;Pasindu.Wijayatilaka@f1solutions.com.au;Josh.Yip@f1solutions.com.au;Hector.Figueroa@f1solutions.com.au"
  #     "AccountingOperationsLogEmailsTo": "UAT_Batching@altf4solutions.com.au;Pasindu.Wijayatilaka@f1solutions.com.au;Josh.Yip@f1solutions.com.au;Hector.Figueroa@f1solutions.com.au"
  #     "EmailBatchingLogEmailsTo": "UAT_Batching@altf4solutions.com.au;Pasindu.Wijayatilaka@f1solutions.com.au;Josh.Yip@f1solutions.com.au;Hector.Figueroa@f1solutions.com.au"
  #     "AccountingOperationsReportEmailsFrom": "uat.ncms_batching@naati.com.au"
  #     "SecurePayResource": "https://payments-stest.npe.auspost.zone"
  #     "SecurePayTokenUrl": "https://welcome.api2.sandbox.auspost.com.au/oauth/token"
  #     "SecurePayJavascriptSDKUrl": "https://payments-stest.npe.auspost.zone/v3/ui/client/securepay-ui.min.js"
  #     "PayPalMode": "sandbox" 
  #     "PayPalConnectionTimeout": "360000" 
  #     "PayPalRequestRetries": "1" 
  #     "WiiseAuthRedirectUri": "https://uatncms.naati.com.au/api/System/WiiseResponse"
  #     "WiiseBaseUrl": "https://api.businesscentral.dynamics.com/v2.0/41bb5789-7441-4051-b270-c49376cfab28/Sandbox12062025/api/v2.0/companies(fed3af4d-b48d-eb11-8ce5-000d3aca5a42)"
  #     "QrCodeAccessUrl": "https://mynaatiuat.naati.com.au/VerifyPractitioner?QrCode={0}"
  # # (Put all configmap values from your example hereâ€¦)

     