replicaCount: 1

image:
  repository: naatidevacri0q0.azurecr.io/naatidevacri0q0.azurecr.io/mynaatiui
  tag: "20250730.14"  # Use the same working tag pattern
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: acr-secret-new

serviceAccount:
  name: kv-reader-sa     

podSecurityContext: {}

containerSecurityContext: {}

nodeName: akse2asv5000000

persistentStorage:
  claimName: dev-naati-volume-claim
  mountPath: /storage

tempPersistentStorage:
  claimName: dev-naati-temp-volume-claim
  mountPath: /tempStorage

env:
  KeyVaultUrl: https://naati-dev-kv-jyrb.vault.azure.net/

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

service:
  type: LoadBalancer
  port: 80
  targetPort: http
  loadBalancerIP: 10.50.4.101
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"

resources: {}

affinity: {}

tolerations: []

terminationGracePeriodSeconds: 15

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  cpu:
    averageUtilization: 80

config:
  "CertificationApiLimit": "3"
  "aspnet_MaxJsonDeserializerMembers": "160000"
  "owin_AutomaticAppStartup": "false"
  "ClientValidationEnabled": "false"
  "UnobtrusiveJavaScriptEnabled": "true"
  "GoogleAnalyticsEnabled": "true"
  "webpages_Enabled": "false"
  "webpages_Version": "3.0.0.0"
  "ExternalUrl_Applications_URL": "https://mynaati.com.au/apply"
  "ExternalUrl_NAATI_URL": "https://www.naati.com.au"
  "ExternalUrl_NAATI": "https://www.naati.com.au/resources/faq/"
  "ExternalUrl_FAQ": "https://www.naati.com.au/resources/faq/"
  "ExternalUrl_PrivacyPolicy": "https://www.naati.com.au/policies/privacy/"
  "ExternalUrl_RefundPolicy": "https://www.naati.com.au/about/our-policies/"
  "ExternalUrl_ShippingPolicy": "https://www.naati.com.au/about/our-policies/"
  "ExternalUrl_TermsAndConditions": "https://www.naati.com.au/policies/terms-and-conditions"
  "ExternalUrl_ContactUs": "https://www.naati.com.au/get-in-touch/get-in-touch/"
  "ExternalUrl_Witness": "https://www.naati.com.au/about/our-policies/"
  "ExternalUrl_AccreditationLevels": "https://www.naati.com.au/media/1109/outline_naati_credentials.pdf"
  "ExternalUrl_AccreditationMethodList": "https://www.naati.com.au/information/accreditation/"
  "ExternalUrl_AccreditationByCourseInformationBooklet": "https://www.naati.com.au/media/1286/accreditation_by_aus_approved_course_information_booklet.pdf"
  "ExternalUrl_AccreditationByTestingInformationBooklet": "https://www.naati.com.au/media/1365/accreditation_by_testing_information_booklet.pdf"
  "ExternalUrl_ApprovedCourseInformation": "https://www.naati.com.au/information/approved-courses/"
  "ExternalUrl_AccreditationByTestingLanguages": "https://www.naati.com.au/media/1137/languages_with_accreditation_testing.pdf"
  "ExternalUrl_ExpressionOfInterestInformation": "https://www.naati.com.au/information/accreditation/"
  "ExternalUrl_FormsAndFees": "https://www.naati.com.au/media/1079/naati_forms_and_fees.pdf"
  "ExternalUrl_RevalidationProducts": "https://www.naati.com.au/media/1409/revalidation_information_booklet.pdf"
  "ActiveReportsLicense": "PERhdGFEeW5hbWljc0xpY2Vuc2UgbmFtZT0iRjEgU29sdXRpb25zIiBlbWFpbD0iZ3VzQGYxc29sdXRpb25zLmNvbS5hdSIgc2VyaWFsPSJERC1BUk4tNjAtRDAxMDczNiIgaG9zdGVkPSJPRE5MTlRJeVV3PT0iPjxMaWNlbnNlS2V5PnptMytRRjZ1TjV2djF6UkxOU1ppMlgram1NcFRabEg5YzhBSWQxUTAwMUo4T2p3WDRYVHJwL3pCY1luS3l4QjRZR2gwMC83YjRHY0lCRThRWnd0emlmWjZxTUQ4Z2JJODwvTGljZW5zZUtleT48U2lnbmF0dXJlIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjIj48U2lnbmVkSW5mbz48Q2Fub25pY2FsaXphdGlvbk1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnL1RSLzIwMDEvUkVDLXhtbC1jMTRuLTIwMDEwMzE1IiAvPjxTaWduYXR1cmVNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjcnNhLXNoYTEiIC8+PFJlZmVyZW5jZSBVUkk9IiI+PFRyYW5zZm9ybXM+PFRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyNlbnZlbG9wZWQtc2lnbmF0dXJlIiAvPjwvVHJhbnNmb3Jtcz48RGlnZXN0TWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnI3NoYTEiIC8+PERpZ2VzdFZhbHVlPm5XN3dTdW9IcndIZjczeGdhN3ZGVlFKYWVuZz08L0RpZ2VzdFZhbHVlPjwvUmVmZXJlbmNlPjwvU2lnbmVkSW5mbz48U2lnbmF0dXJlVmFsdWU+alEwRHVGQW9HNjA4ZzdSRkRmV3ZtSFplUnFra1Ric2JwY3daUXR1d2VrdHhheVFIdGFRMGt4VXlML08vdEwrNDY2aDFncm9SVTVvc255bTdMeGpoL0E9PTwvU2lnbmF0dXJlVmFsdWU+PC9TaWduYXR1cmU+PC9EYXRhRHluYW1pY3NMaWNlbnNlPg=="
  "DownloadApplicationForCredentialByTestingPDFName": "Application for Credentials by Testing Form.pdf"
  "DownloadApplicationForCredentialByCoursePDFName": "Application for Credentials by Australian Course Form.pdf"
  "DownloadApplicationForAssessmentPDFName": "Application Assessment Educational Quals Skilled Employment.pdf"
  "BypassExaminerAuthentication": "false"
  "ExcludedNamesList": ""
  "NcmsUrl": "dev-ncms"
  "tempFilePath": "c:\\tempStorage\\TemporaryFiles"
  "applicationData": "c:\\storage\\ContainerData\\MyNaati"
  "IncludedFileExtensionsList": "bmp,csv,doc,docx,gif,jpg,jpeg,pdf,png,pps,ppt,pptx,ppsx,rtf,tiff,txt,xls,xlsx,xml,zip,mp3,wma,wav,aiff,webm,mkv,flv,avi,mov,qt,wmv,rm,rmvb,mp4,m4p,m4v,mpg,mp2,mpeg,mpv,mpe,m2v,asf,divx,msg,m4a,m4b"
  "kosettings_allowEmailPaste": "false"
  "kosettings_skipRecaptcha": "false"
  "EmailChangeValidHours": "24"
  "logging_SeqUrl": "https://seq.f1solutions.com.au"
  "logging_SeqLogBufferFileBase": "seqBuffer"
  "logging_LogFile": "app.log"
  "logging_DiagnosticsLogFile": "loggingDiagnostics.log"
  "EnvironmentType": "UAT"
  "EnvironmentName": "UAT_CLOUD"
  "DebugMode": "false"
  "EnableSwagger": "false"
  "logging_MinimumLevel": "Information"
  "fileSystemFileStorageServiceBasePath": "c:\\storage\\FileStorage"
  "StorageUriTemplate": "https://{0}.file.core.windows.net/{1}/{2}"
  "StorageAccountTemplate": "DefaultEndpointsProtocol=https;AccountName={0};AccountKey={1};EndpointSuffix=core.windows.net"
  "GraphResourceId": "https://graph.microsoft.com/"
  "GraphApiBaseUrl": "https://graph.microsoft.com/v1.0"
  "GraphTokenUrl": "https://login.microsoftonline.com/common/oauth2/token"
  "SearchResultLimit": "500"
  "SecurePay_PaymentUrl": "https://api.securepay.com.au/xmlapi/payment"
  "SecretPrefix": "UAT"
  "PDSearchResults_MinimumCacheRefreshInterval": "30"
  "DesiredTimeZone": "AUS Eastern Standard Time"
  "HttpsConfigured": "true"
  "SASDemoFile": ""
  "MyNaatiPodUrl": "http://"
  "MaxPublicApiResults": "200"
  "DefaultAppLocalUrl": "https://mynaati.com.au"
  "secrets_Source": "AzureKeyVault"
  "AuthenticationFormsTimeout": "15"
  "MaxUserRefreshDelaySeconds": "15"
  "Culture": "en-AU"
  "EncodeAttributeExpressions": "(/&gt;[\\s\\S\\r\\n]*&lt;script&gt;[\\s\\S\\r\\n]*&lt;/script&gt;),(&lt;script&gt;[\\s\\S\\r\\n]*&lt;/script&gt;),(&lt;script&gt;),(&lt;/script&gt;)"
  "UiCulture": "en-AU"
  "OnlineDirectoryUrl": "https://www.naati.com.au"
  "OnlineHelpUrl": "https://www.naati.com.au"
  "AccountingOperationsReportEmailsTo": "admin@naati.com.au"
  "EmailBatchingReportEmailsTo": "admin@naati.com.au"
  "AccountingOperationsLogEmailsTo": "admin@naati.com.au"
  "EmailBatchingLogEmailsTo": "admin@naati.com.au"
  "AccountingOperationsReportEmailsFrom": "noreply@naati.com.au"
  "SecurePayResource": "https://payments-stest.npe.auspost.zone"
  "SecurePayTokenUrl": "https://welcome.api2.sandbox.auspost.com.au/oauth/token"
  "SecurePayRedirectUri": ""
  "SecurePayScope": "https://api.payments.auspost.com.au/payhive/payments/read https://api.payments.auspost.com.au/payhive/payments/write"
  "SecurePayJavascriptSDKUrl": "https://payments-stest.npe.auspost.zone/v3/ui/client/securepay-ui.min.js"
  "PayPalMode": "live"
  "PayPalConnectionTimeout": "360000"
  "PayPalRequestRetries": "1"
  "WiiseBaseUrl": "https://wiise.api.bc.dynamics.com/v2.0/41bb5789-7441-4051-b270-c49376cfab28/NAATISandbox/api/v2.0"
  "WiiseResource": "https://api.businesscentral.dynamics.com"
  "WiiseResponseRedirect": "~/#system/setup/WiiseAuthSuccess"
  "WiiseTokenUrl": "https://login.windows.net/41bb5789-7441-4051-b270-c49376cfab28/oauth2/token?resource=https://api.businesscentral.dynamics.com"
  "WiiseAuthRedirectUri": "https://mynaati.com.au/api/System/WiiseResponse"
  "WiiseRandomErrorsEnabled": "false"
  "QrCodeAccessUrl": "https://mynaati.com.au/VerifyPractitioner?QrCode={0}"
