apiVersion: v1
kind: Secret
metadata:
  name: {{ include "naati-infra.keyVaultSecret" . }}
  #namespace: development
type: Opaque
data:
  # Base64_Encoded account name
  KeyVaultClientId: {{ .Values.keyVaultClientId | b64enc  }}
  # Base64_Encoded key
  KeyVaultClientSecret:  {{ .Values.keyVaultSecret | b64enc  }}
  # Base64_Encoded url
  KeyVaultUrl:  {{ .Values.keyVaultUrl | b64enc  }}