apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "naati-infra.machineKeySecret" . }}	
  #namespace: development
type: Opaque
data:
  # Base64_Encoded machine key
  validationKey:  {{ .Values.machineValidationKey | b64enc  }}
  # Base64_Encoded description key
  decryptionKey: {{ .Values.machineDescriptionKey | b64enc  }}
