apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "naati-infra.storageSecret" . }}	
  #namespace: development
type: Opaque
data:
  # Base64_Encoded account name
  azurestorageaccountname: {{ .Values.azureStorageAccountName | b64enc  }}
  # Base64_Encoded key
  azurestorageaccountkey:  {{ .Values.azureStorageAccountKey | b64enc  }}