apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "naati-infra.persistentStorage" . }}	 
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    # Replace with your secret name
    secretName: {{ include "naati-infra.storageSecret" . }}
    # Replace with correct storage share name
    shareName: {{ include "naati-infra.storageShareName" . }}
    # In case the secret is stored in a different namespace
    #shareNamespace: default
    readOnly: false
  mountOptions:
    - dir_mode=0777
    - file_mode=0777