apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "naati-infra.tempStorageSecret" . }}	
  #namespace: development
type: Opaque
data:
  # Base64_Encoded account name
  azurestorageaccountname: {{ .Values.azureStorageAccountNameTemp | b64enc  }}
  # Base64_Encoded key
  azurestorageaccountkey:  {{ .Values.azureStorageAccountKeyTemp | b64enc  }}