{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mynaati.serviceAccountName" . }}
  labels:
{{ include "mynaati.labels" . | nindent 4 }}
{{- end -}}
