pv:
  storageClassName: standard
  capacity: 1Gi
  accessMode: ReadWriteMany
  reclaimPolicy: Retain
  azureFile:
    secretName: dev-naati-storage
    shareName: app-files-share
    readOnly: false

pvTemp:
  storageClassName: standard
  capacity: 1Gi
  accessMode: ReadWriteMany
  reclaimPolicy: Retain
  azureFile:
    secretName: dev-naati-temp-storage
    shareName: temp-files-share
    readOnly: false

pvc:
  namespace: default
  accessMode: ReadWriteMany
  storage: 1Gi
  storageClassName: standard


pvcTemp:
  namespace: default
  accessMode: ReadWriteMany
  storage: 1Gi
  storageClassName: standard

azureFileTemp:
  accountName: bmFhdGlkZXZhcHBmaWxlc3RlbXBpMHEwCg==
  accountKey: blRQWnFzVHlENFBrbExBQ2FCbkpiWHE4ZUMxVHVWdmNMUS84MTZKMmdkVnpGY05YaXVOV0tuR2RvT1NwbWxMUFh1c044bjFNTVZSTitBU3RubHQ3ZFE9PQo=
secret:
  namespace: default
  accountName: bmFhdGlkZXZhcHBmaWxlc2kwcTAK
  accountKey: QXZTcmdubUI3MjU5VnRrbVRVa2kvZFh2a3lGM1lLdGUxenFFSUlmYTJWYW5HRzhTcVpWV1ZqL1RFQmt1VFpnK3ZNYkRvQnBBRWZLUStBU3RpUzBHWGc9PQo=
acrSecret:
  namespace: default
  dockerconfigjson: eyJhdXRocyI6eyJuYWF0aWRldmFjcmkwcTAuYXp1cmVjci5pbyI6eyJ1c2VybmFtZSI6Im5hYXRpZGV2YWNyaTBxMCIsInBhc3N3b3JkIjoiZkdUQldQdDdqL0ZWL09XcFJ4WDdHOXpST2lid2M2V1BqNU5qNTJBY3RIK0FDUkFBcmwwbiIsImF1dGgiOiJibUZoZEdsa1pYWmhZM0pwTUhFd09tWkhWRUpYVUhRM2FpOUdWaTlQVjNCU2VGZzNSemw2VWs5cFluZGpObGRRYWpWT2FqVXlRV04wU0N0QlExSkJRWEpzTUc0PSJ9fX0=

