apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-ncms
data:
  # Configuration values can be set as key-value properties 
  "sam_SearchResultLimit": "500"
  "sam_defaultAssetFileName": "[TestAttendanceId] - [Skill] [Date] [UniqueID] - [DocumentType]"
  "tempFilePath": "c:\\tempStorage\\TemporaryFiles"
  "applicationData": "c:\\storage\\ContainerData\\Ncms"
  "sam_IncludedFileExtensionsList": "bmp,csv,doc,docx,gif,jpg,jpeg,pdf,png,pps,ppt,pptx,ppsx,rtf,tiff,txt,xls,xlsx,xml,zip,mp3,wma,wav,aiff,webm,mkv,flv,avi,mov,qt,wmv,rm,rmvb,mp4,m4p,m4v,mpg,mp2,mpeg,mpv,mpe,m2v,asf,divx,msg,m4a,m4b"
  "AadResponseRedirect": "~/#system/setup/AzureAuthSuccess"
  "AadAuthScope": "openid offline_access https://graph.microsoft.com/mail.read https://graph.microsoft.com/mail.read.shared https://graph.microsoft.com/user.read"
  "AccountingOperationsReportEmailsTo": "LOCALHOST@altf4solutions.com.au"
  "EmailBatchingReportEmailsTo": "Hector.Figueroa@f1solutions.com.au"
  "AccountingOperationsLogEmailsTo": "LOCALHOST@altf4solutions.com.au"
  "EmailBatchingLogEmailsTo": "Hector.Figueroa@f1solutions.com.au"
  "AccountingOperationsReportEmailsFrom": "localhost.noreply@altf4solutions.onmicrosoft.com"
  "logging_SeqUrl": "https://seq.f1solutions.com.au"
  "logging_SeqLogBufferFileBase": "seqBuffer"
  "logging_LogFile": "app.log"
  "logging_DiagnosticsLogFile": ""
  "EnvironmentType": "uat"
  "EnvironmentName": "UAT_CLOUD"
  "ShowAllMenuItems": "False"
  "DebugMode": "False"
  "GoogleApiKey": "AIzaSyCAB7XeHbps7BDx6uw-plZKEHSg-lVM_KY"
  "fileSystemFileStorageServiceBasePath": "c:\\storage\\FileStorage"
  "StorageUriTemplate": "https://{0}.file.core.windows.net/{1}/{2}"
  "StorageAccountTemplate": "DefaultEndpointsProtocol=https;AccountName={0};AccountKey={1};EndpointSuffix=core.windows.net"
  "GraphResourceId": "https://graph.microsoft.com/"
  "GraphApiBaseUrl": "https://graph.microsoft.com/v1.0"
  "GraphTokenUrl": "https://login.microsoftonline.com/common/oauth2/token"
  "AadAuthRedirectUri": "https://uatncms.naati.com.au/api/System/AadResponse"
  "SearchResultLimit": "500"
  "SecurePay_PaymentUrl": ""
  "logging_MinimumLevel": "Information"
  "AzureAppAuthority": "https://login.microsoftonline.com/{0}/v2.0"
  "AzureAppRedirectUri": "https://uatncms.naati.com.au"
  "MyNaatiUrl": "my-mynaati-release-mynaati"
  "SecretPrefix": "UAT"
  "ScriptsTimeoutSeconds": "500"
  "DesiredTimeZone": "AUS Eastern Standard Time"
  "HttpsConfigured": "true"
  "NcmsPodUrl": "dev-ncms"
  "DefaultAppLocalUrl": "hhttp://127.0.0.1/"
  "SASDemoFile": " "
  "secrets_Source": "AzureKeyVault"
  "AuthenticationFormsTimeout": "15"
  "ReportingJobName": "NCMSReportingDatabase"
  "ReportingJobDatabaseName": "msdb"
  "MaxUserRefreshDelaySeconds": "15"
  "EncodeAttributeExpressions": "(/&gt;[\\s\\S\\r\\n]*&lt;script&gt;[\\s\\S\\r\\n]*&lt;/script&gt;),(&lt;script&gt;[\\s\\S\\r\\n]*&lt;/script&gt;),(&lt;script&gt;),(&lt;/script&gt;)"
  "Culture": "en-AU"
  "UiCulture": "en-AU"
  "SecurePayResource": "https://payments-stest.npe.auspost.zone"
  "SecurePayTokenUrl": "https://welcome.api2.sandbox.auspost.com.au/oauth/token"
  "SecurePayRedirectUri": ""
  "SecurePayScope": "https://api.payments.auspost.com.au/payhive/payments/read https://api.payments.auspost.com.au/payhive/payments/write"
  "PayPalMode": "sandbox"
  "PayPalConnectionTimeout": "360000"
  "PayPalRequestRetries": "1"
  "WiiseBaseUrl": "https://wiise.api.bc.dynamics.com/v2.0/41bb5789-7441-4051-b270-c49376cfab28/naatisandbox/api/v2.0/companies(d96ec21b-1177-eb11-b855-000d3a6a22b9)"
  "WiiseResource": "https://api.businesscentral.dynamics.com"
  "WiiseResponseRedirect": "~/#system/setup/WiiseAuthSuccess"
  "WiiseTokenUrl": "https://login.windows.net/41bb5789-7441-4051-b270-c49376cfab28/oauth2/token?resource=https://api.businesscentral.dynamics.com"
  "WiiseAuthRedirectUri": "https://uatncms.naati.com.au/api/System/WiiseResponse"


  "WiiseRandomErrorsEnabled": "false"
  "TestSittingsWithoutMaterialReminderEmailAddresses": ""
  "QrCodeAccessUrl": "https://mynaatiuat.naati.com.au/VerifyPractitioner?QrCode={0}"
