replicaCount: 1

image:
  repository: naatidevacri0q0.azurecr.io/naatidevacri0q0.azurecr.io/ncmsui
  tag: "20250730.14"  # Use the working tag from your successful pod
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: acr-secret-new

nodeName: akse2asv5000000

serviceAccount:
  name: kv-reader-sa

persistentStorage:
  claimName: dev-naati-volume-claim
  mountPath: /storage

tempPersistentStorage:
  claimName: dev-naati-temp-volume-claim
  mountPath: /tempStorage

env:
  KeyVaultUrl: https://naati-dev-kv-jyrb.vault.azure.net/

service:
  loadBalancerIP: 10.50.4.100
  type: LoadBalancer
  port: 80
  targetPort: http
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"

podSecurityContext: {}
containerSecurityContext: {}
terminationGracePeriodSeconds: 15

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

affinity: {}

tolerations: []

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  cpu:
    averageUtilization: 80

# Add more if needed
