apiVersion: v1
kind: Service
metadata:
  name: my-mynaati-release-mynaati   # MANUAL NAME
  labels:
    helm.sh/chart: mynaati-1.0.0
    app.kubernetes.io/name: mynaati
    app.kubernetes.io/instance: my-mynaati-release
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: mynaati
    app.kubernetes.io/instance: my-mynaati-release
